### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by hosseinian** [amirhosseinchoghaei/Passwall#10]
Thanks. Everything is working, and installation was straightforward, but I have a performance issue on mi a4 gigabit. The memory seems insufficient to handle the process, and I have randomly crashed and rebooted the router. Do you have any advice to increase the available memory to handle the process?

**Comment by amirhosseinchoghaei** [comment]
Hi Mohsen, When You installed The Script ? 
1 month ago ?

**Comment by hosseinian** [comment]
I installed it yesterday.

**Comment by amirhosseinchoghaei** [comment]
Unfortunately, there is no advice ! 
But in the Latest Update of script , i set the timer to check Passwall is Available or not … if memory kill the passwall , the script Will Reload Passwall Automatically Without Any reboot .
Timer interval : 1 minutes

**Comment by hosseinian** [comment]
Yes, by the way, thanks for your useful script.

**Comment by amirhosseinchoghaei** [comment]
May i ask you something !?
When Passwall Crashed And you want to reboot , 
Before that ,, remote SSH to openwrt and use this command : 

sh timer.sh

then send me the text results 

thank you 🙏

**Comment by tkmw1985** [comment]
May be Zram help you
