### ISSUE TITLE
Need to change the ip address to install the script

### ISSUE THREAD

**Issue by arash1959** [amirhosseinchoghaei/Passwall#11]
سلام مهندس جان اکثر مواقع لازم حتما آدرس پیشفرض اپن دبلیو آرتی عوض بشه تا نصب انجام بشه یعنی از 192.168.1.1 تغییر کنه به آدرس دیگه ای آیا راهی هست خود اسکریپت اول آدرس رو تغییر بده بعد نصب انجام بده سپاس

**Comment by amirhosseinchoghaei** [comment]
درود ، در انتهای اسکریپت آی پی شما تغییر داده میشه و به 192.168.27.1 تبدیل میشه ! اگر اول انجام بشود ارتباط شما با کنسول قطع میشه و فرآیند نصب به مشکل خواهد خورد ...
