### ISSUE TITLE
INSTALL OPENWRT 22.03.05

### ISSUE THREAD

**Issue by freeforlife-star** [amirhosseinchoghaei/Passwall#14]
سلام
باتشکر از آموزش خوب و کاربردیتون
چطور میشه این ورژن رو نصب کرد، تو خود سایت برای مودم xiaomi 4a giga فقط ورژن 23.05 برای دانلود قرارداده شده
لطفا راهنمایی می فرمایید
ممنون

**Comment by amirhosseinchoghaei** [comment]
https://downloads.openwrt.org/releases/22.03.5/targets/ramips/mt7621/openwrt-22.03.5-ramips-mt7621-xiaomi_mi-router-4a-gigabit-squashfs-sysupgrade.bin
