### ISSUE TITLE
HYSTERIA 2

### ISSUE THREAD

**Issue by arash1959** [amirhosseinchoghaei/Passwall#15]
سلام و خسته نباشید مهندس آیا امکان اضافه کردن هیستریا هست و اینکه چطور میشه passwall رو به ورژن  4.71.3 آپگرید کرد سپاس

**Comment by amirhosseinchoghaei** [comment]
درود بر شما ، هیستریا زیر مجموعه ساین باکس هستش ، مدل روتر شما چی هستش ؟

**Comment by arash1959** [comment]
xiaomi router 4a gigabi

**Comment by amirhosseinchoghaei** [comment]
به زودی آپدیت منتشر میشه که میتونید سینگ باکس را جایگزین ایکس ری کنید ...

**Comment by arash1959** [comment]
تشکر از زحماتت مهندیس منتظر آپدیت هستیم سپاس

**Comment by amirhosseinchoghaei** [comment]
آپدیت جدید منتشر شد ، حالا میتونید sing-box را که پرتکل های tuic و hysteria2 را ساپورت میکند نصب کنید با دستور زیر :

rm -f amirhossein.sh && wget https://raw.githubusercontent.com/amirhosseinchoghaei/mi4agigabit/main/amirhossein.sh && chmod 777 amirhossein.sh && sh amirhossein.sh

دقت کنید که فقط یکی از هسته ها را میتوانید نصب کنید یا ایکس ری یا سینگ-باکس 

درصورت موفق آمیز بودن همینجا اطلاع بدید ممنون ...

**Comment by arash1959** [comment]
سلام مهندس بسیار عالی خسته نباشید حتما اطلاع میدم ❤️

**Comment by arash1959** [comment]
مهندس جان نصب انجام شد فقط اینکه ادلینک رو که میزنم هیستریا و توئیک رو قبول نمیکنه  تو قسمت آپدیت هم سینباکس نصب شده نشون میده  آیا کار خاصی باید انجام بشه من توئیک رو از ایزی پیزی استفاده میکنم

**Comment by amirhosseinchoghaei** [comment]
باید دستی وارد کنید اطلاعات رو برای هیستریا و توئیک ، گزینه add را بزنید و با توجه به کانفیگی که دارید وارد بفرمایید ... میتونید از نکوری کمک بگیرید و اطلاعات را جایگزاری کنید ...
