### ISSUE TITLE
قطع و وصل شدن tuic 

### ISSUE THREAD

**Issue by arash1959** [amirhosseinchoghaei/Passwall#16]
سلام مهندس  تیک خوردن tcping در قسمت node list باعث قطع و وصل شدن tuic میشه احتمالا برای هیستریا هم همین مشکل رو ایجاد بکنه به نظرم اون تیک دیفالت نباشه بهتره همینطور وقتی  touch check instagram رو هم میزنم کانفیگ رو قطع میکنه سپاس

**Comment by amirhosseinchoghaei** [comment]
چه عجیب من حدود دوماه دارم از tuic استفاده میکنم مشکلی ندیدم ... ورژن Openwrt شما چند هستش ؟

**Comment by arash1959** [comment]
22.03.5 مهندس جان جالب اینه هم ایکس ری نصب هست هم سینباکس  نمیدونم شاید واسه همینه مشکل خورده

**Comment by amirhosseinchoghaei** [comment]
توی قسمت app update که میرید ایکس ری ورژن خورده ؟

**Comment by arash1959** [comment]
بله 1.8.6

**Comment by arash1959** [comment]
الان هم میتونم ریلیتی استفاده کنم هم توئیک

**Comment by amirhosseinchoghaei** [comment]
هردو نصب باشه اختلال میخورید رمتون پر میشه 
روتر رو خاموش روشن کنید لطفا
