### ISSUE TITLE
مشکل نصب

### ISSUE THREAD

**Issue by arianaminiss** [amirhosseinchoghaei/Passwall#19]
سلام وقت بخیر روتر شیائومی 4a gigabit مشکل نصب دارم انگار یه پکیج رو نمیتونه دانلود کنه باید چیکار کنم؟
![Screenshot 2024-01-13 005643](https://github.com/amirhosseinchoghaei/Passwall/assets/120175590/d76f3c10-d02b-461c-9252-2ff9437ebc3c)
![Screenshot 2024-01-13 005526](https://github.com/amirhosseinchoghaei/Passwall/assets/120175590/e8e2eaab-9e36-40c7-b63c-26266ceb5777)
![Screenshot 2024-01-13 005321](https://github.com/amirhosseinchoghaei/Passwall/assets/120175590/4a8f062e-3d01-4fa1-bba6-05b8dba17742)

**Comment by amirhosseinchoghaei** [comment]
درود ، روی هاست دانلود اختلال هستش برای نصب وی پی ان سیستم را به اشتراک بزارید روی لن تا بتونه دانلود کنه …

**Comment by arianaminiss** [comment]
ببخشید یه سوالی داشتم امکانش هست بشه کاری کرد که کلا درخواست های پورت 3074 از تانل رد نشن؟ توی بخش access control دیوایس مورد نظر برای تنظیمات ادد شده این پورته هم مربوطه به یه بازی هست که فقط از همین پورت استفاده میکنه میخوام کلا اگه بشه تنظیم کنم این پورته هیچ ترافیک vpn ای بهش داده نشه امکانش هست؟

**Comment by amirhosseinchoghaei** [comment]
سلام
توی قسمت other setting 
سکشن TCP No Redir Ports رو بزنید و قسمت کاستوم پروت مورد نظر را وارد کنید و اینتر رو بزنید و سیو کنید 
در آخر از بخش دی ان اس پسوال clear ipset رو بزنید 

موفق باشید
