### ISSUE TITLE
Amirhossein everywhere!

### ISSUE THREAD

**Issue by theonlyfoxy** [amirhosseinchoghaei/Passwall#2]
Haji gaiidi ba amirhossein, to banner ssh ham amirhossein akhe ? :|
[everywhere i go...](https://i.pinimg.com/originals/05/42/a5/0542a568280eaff0cd2dfadbfa362ecd.jpg)

**Comment by amirhosseinchoghaei** [comment]
😂😂😂😂 taze esm wifi haro ham mikhastam bezanam amirhossein dg khodam halam dasht beham mikhord ...
