### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by MrSaeid007** [amirhosseinchoghaei/Passwall#23]
سلام @amirhosseinchoghaei 

لطفا یه اسکرپت نصب passwall برامون تهیه کن که بتونیم روی روتر شیائومی 4A (100M Edition) که فضای temp اش 28 مگ هست از شادوساکس حداقل بتونیم استفاده کنیم.

تشکر.

**Comment by amirhosseinchoghaei** [comment]
درود، طبق ویدیو یوتیوب پیش برید به نتیجه میرسید ...

https://www.youtube.com/watch?v=AjWVyHKblm8&t=10s&ab_channel=AmirHosseinChoghaei
