### ISSUE TITLE
How much ram Openwrt 22.03.3 will save?

### ISSUE THREAD

**Issue by firefoxOnFire** [amirhosseinchoghaei/Passwall#26]
[IF you have Xiaomi 4a Gigabit , Openwrt 22.03.3 Recommended](https://archive.openwrt.org/releases/22.03.3/targets/ramips/mt7621/openwrt-22.03.3-ramips-mt7621-xiaomi_mi-router-4a-gigabit-squashfs-sysupgrade.bin) -> from readme

How much ram it will save? can you show the screenshot?

I am on version after this update, and have setup many things, so before downgrading, i want to be sure if it would be productive or not.

Thanks.

**Comment by amirhosseinchoghaei** [comment]
Hi , What is your firmware version ?

**Comment by amirhosseinchoghaei** [comment]
version 22.03.3 is better for you , don't keep setting while downgrading .

if you want to upgrade to latest version Buy Xiaomi AX3000T

**Comment by amirhosseinchoghaei** [comment]
https://archive.openwrt.org/releases/22.03.3/targets/ramips/mt7621/openwrt-22.03.3-ramips-mt7621-xiaomi_mi-router-4a-gigabit-squashfs-sysupgrade.bin

system > backup / flash > flash image
