### ISSUE TITLE
Fragment and Warp

### ISSUE THREAD

**Issue by insightde** [amirhosseinchoghaei/Passwall#27]
Hi Amir, Thanks for your hard work.
Can you please guide us on how we can import fragment.json config? 
I saw you mentioned something about fragment added.
Another question is can we add warp://auto config too?
thanks bro ;)

**Comment by amirhosseinchoghaei** [comment]
Hi there , Update your Passwall , Go to > other setting and you see the fragment option with tlshello and 1-3 added .
when you turn on this option , should work on xray nodes Automatically to bypass SNI Restriction .
unfortunately there is no way to edit .Jason for warp ! maybe in future ...
