### ISSUE TITLE
Connection Drop After About 5-10 Minutes

### ISSUE THREAD

**Issue by aminsamizadeh** [amirhosseinchoghaei/Passwall#3]
Testing with Some Configs but found out after about 5-10 minutes connections drops and needs to change the config to bring back the connection temporarily ... and so on...
What about "Auto Switch" function? That would help in this situation i think... Any idea to have it back?
The Device is Xiaomi 4A Gigabit ...

**Comment by aminsamizadeh** [comment]
Hi Amir Hossein,
The one you made the instruction to install ... 
OpenWrt Version : 22.03.4

**Comment by amirhosseinchoghaei** [comment]
i said passwall bro ... check it at app update

**Comment by aminsamizadeh** [comment]
4.70-9-smartdns-dev

**Comment by amirhosseinchoghaei** [comment]
Cool !
Send Me your anydesk code to my telegram :
