### ISSUE TITLE
مشکل اتصال

### ISSUE THREAD

**Issue by borderlessnet** [amirhosseinchoghaei/Passwall#30]
وقت بخیر؛
من پکیج قدیمیتون رو (فقط نصب xray) روی یک روتر دیگه دارم و خیلی عالی کار میکنه اما در پکیج جدید (هم نصب xray به تنهایی و هم نصب passwall کامل ) بعد از وارد کردن کانفیگ، گوگل با آی پی کانفیگ باز میشه و چک آی پی، درست هست اما متاسفانه سایتهای فیلتر مثل یوتیوب باز نمیشه، اما اپلیکیشن تلگرام دسکتاپ و تلگرام موبایل و همینطور واتساپ باز میشن. همین کانفیگ در روتر قدیمی بدون مشکل کار میکنه
هر دو روتر xiaomi 4a gig و openwrt ورژن 23.03

**Comment by amirhosseinchoghaei** [comment]
درود ، دی ان اس هاتون رو چک کنید مشکل از سمت دی ان اس شما هست

**Comment by borderlessnet** [comment]
با عرض پوزش، این که فرمودید رو هم انجام دادم، از دیروز هم تمام حالتهاش رو با دی ان اس های مختلف و حتی تغییر دی ان اس مودم دارم تست میکنم اما متاسفانه جواب نمیده و به همون وضعیت هست.

**Comment by amirhosseinchoghaei** [comment]
لطفا تلگرام پیام دهید
