### ISSUE TITLE
مشکل - تغییر نکردن ای پی

### ISSUE THREAD

**Issue by rbsdotnet** [amirhosseinchoghaei/Passwall#33]
درود دوست عزیز
بعد از نصب آی پی تغییر نمیکنه و آی پی ایران رو نمایش میده
اما Youtube و سایر سایت هایی که فیلتر هستن بدون مشکل باز میشن
مشکل از چی هست؟

**Comment by amirhosseinchoghaei** [comment]
DNS

**Comment by rbsdotnet** [comment]
درود
من تمام dns ها رو بررسی کردم جواب نداد
فقط در صورتی جواب میده که tcp default proxy mode در حالت proxy باشه
این مشکل در نسخه جدید وجود داره

![Screenshot 2024-03-06 at 20-39-17 OpenWrt - Basic Settings - LuCI](https://github.com/amirhosseinchoghaei/Passwall/assets/49598914/d893fa21-00da-44dc-9af6-ece8acfbac8c)

**Comment by amirhosseinchoghaei** [comment]
درود ، هم tcp و هم udp باید در حالت proxy باشند ...

**Comment by rbsdotnet** [comment]
> درود ، هم tcp و هم udp باید در حالت proxy باشند ...

پیش فرض این بخش فعال نیست ممنون از راهنمایی شما
