### ISSUE TITLE
After installing x-ray on the tmp folder

### ISSUE THREAD

**Issue by AllenfrankX** [amirhosseinchoghaei/Passwall#35]
Good afternoon, I installed everything on tmp folder and after reboot everything disappears, how can I fix this, can you help please?

**Comment by amirhosseinchoghaei** [comment]
Hi there , if you install with my script , after reboot the xray will download automatically .

what is your router ?

**Comment by AllenfrankX** [comment]
> Hi there , if you install with my script , after reboot the xray will download automatically .
> 
> what is your router ?

Mi4A gigabit edition Sir, I install via tmp folder

**Comment by amirhosseinchoghaei** [comment]
rm -f amirhossein.sh && wget https://raw.githubusercontent.com/amirhosseinchoghaei/mi4agigabit/main/amirhossein.sh && chmod 777 amirhossein.sh && sh amirhossein.sh



try this command

**Comment by AllenfrankX** [comment]
Also delete x-ray after reboot system

**Comment by AllenfrankX** [comment]
Work, thanks
