### ISSUE TITLE
Passwall 1 vs Passwall 2

### ISSUE THREAD

**Issue by arash1959** [amirhosseinchoghaei/Passwall#36]
سلام مهندس خسته نباشی زدم آپگرید بشه دو تا گزینه اومد پسوال ۱ و ۲  برای شیاومی گیگابایت  کدوم رو بزنیم و فرقشون چیه OpenWrt 22.03.5

**Comment by amirhosseinchoghaei** [comment]
درود ، پسوال 2 نسخه لایت و بهینه پسوال 1 هستش ، پسوال 1 امکانات بیشتری بهتون میده ، روی روتر شما پیشنهاد میکنم پسوال 1 نصب بفرمایید .
