### ISSUE TITLE
add iran geoip

### ISSUE THREAD

**Issue by mmddks** [amirhosseinchoghaei/Passwall#37]
Hi.
please add geoip and geosite iran
from this fork to passwall
https://github.com/bootmortis/iran-hosted-domains

**Comment by amirhosseinchoghaei** [comment]
درود ، این دو مورد نیازمند حجم نسبتا زیادی هستند که برای تمام روتر ها قابلیت اجرا ندارد ... لطفا دستی تنظیم کنید اگر فضای دیسک بالایی دارید ... !
