### ISSUE TITLE
problem on ports

### ISSUE THREAD

**Issue by 3245** [amirhosseinchoghaei/Passwall#38]
hello
i installed and all is fine, just issue i have is, my linksys modem has 4x output lan port, they not have internet, but wifi is fine
should i do any extra setting for one of the ports have internet?

if possible please give me your telegram we troubleshoot together

Thanks

**Comment by 3245** [comment]
if possible please give me your telegram we troubleshoot together

**Comment by amirhosseinchoghaei** [comment]
do not use static dns in your lan client ....
use dynamic dns on your pc or any client .

**Comment by 3245** [comment]
منظورتون اینه توی روتر تنطیمی باید انجام بدم؟
چون من داخل کلاینت تنطیمی انجام ندادم و کلن یک تلویزیون رو وصل کردم به روتر از طریق لن که اصلا تنطیمات دی ان اس اینها نداره، اما بازم اینترنت نداره
تنظیماتی باید توی روتر انجام بدم؟
وایفا درست کار میکنه و وی پی ان هم داره، اما هیچکدوم از ۴تا پورتِ روتر اینترنت نداره

تشکر

**Comment by amirhosseinchoghaei** [comment]
اگر زمان اتصال به پورت های lan آی پی دریافت میکنید همه چیز درست هستش ، فقط باید دی ان اس رو بزارید روی حالت اتوماتیک
اگر هم که اصلا آی پی دریافت نمیکنید از سمت روتر مشکل چیز دیگری هستش ریست فکتوری کنید

**Comment by 3245** [comment]
یکسری تصاویر ضمیمه کردم ممکنه چک کنید و بگید آیا درسته این قسمت ها؟ چون واقعا اذیت میکنه🙏❤️
اگر از قسمت دیگه ای نیاز هست بگین عکس بدم
مدل روتر Linksys WRT1900ACS  

![IMG_1499](https://github.com/amirhosseinchoghaei/Passwall/assets/25947915/37c28c7a-8121-4aa5-ac65-aaaaccb2ad51)
![IMG_1500](https://github.com/amirhosseinchoghaei/Passwall/assets/25947915/5b175e65-0a93-4667-bb5d-e68efc675052)
![IMG_1501](https://github.com/amirhosseinchoghaei/Passwall/assets/25947915/6bf55f29-5b0e-49a4-a6e6-1fa684541bfb)
![IMG_1502](https://github.com/amirhosseinchoghaei/Passwall/assets/25947915/98a27f34-21c5-4bc6-849a-fd284705d793)
![IMG_1504](https://github.com/amirhosseinchoghaei/Passwall/assets/25947915/5d386d51-3fbc-43bb-bfb5-918ea8531ea1)
![IMG_1503](https://github.com/amirhosseinchoghaei/Passwall/assets/25947915/4d929146-52cb-4e84-8d2d-b8b10f46a209)

**Comment by amirhosseinchoghaei** [comment]
سلام همه چیز درست هستش ، موبایل یا لپ تاب از دی ان اس استاتیک استفاده نکنید و روی حالت اتوماتیک باشه
