### ISSUE TITLE
ارور دانلود از sourecforge

### ISSUE THREAD

**Issue by mhd13671367** [amirhosseinchoghaei/Passwall#4]
فایل های که لینک sourceforge  دارند دانلود نمیشن با همراه اول شاتل و مخابرات امتحان کردم
فقط سه تا لینک sourceforge 
امکان اش نیست از جای دیگه اونا رو دریافت کرد ؟
نسخه اسنبشات

**Comment by amirhosseinchoghaei** [comment]
درود ، انقدر opkg update رو بزنید تا بدون ارور اکی بده بعد از اینکه ارور نداد کامند نصب که قرار دادم مخصوص اسنپ شات ران کنید
چاره ای نیست … من با مخابرات هم این مشکل را دارم اما چندبار تلاش کنید اکی میشه

**Comment by Wasoud** [comment]
Hi
Here is two way:

1- For this problem can install wireguard package and add new interface by using cloudflare-warp profile. 

OR 

2- simply you can change your DNS from interface > lan > Advanced Settings and use custom DNS 1.1.1.1 Resolve is fix.

**Comment by mhd13671367** [comment]
یا dns 1.1.1.1 هم نشد راهنمای تنظیم وایرگارد و cloadflare warp رو می فرمایید؟

**Comment by amirhosseinchoghaei** [comment]
عرض کردم جناب دستور opkg update رو انقدر وارد بفرمایید تا بدون ارور تکمیل بشه سپس دستور نصب را وارد کنید ...
