### ISSUE TITLE
مشکل با فراگمنت 

### ISSUE THREAD

**Issue by worldamazingplaces** [amirhosseinchoghaei/Passwall#43]
سلام یه مشکلی هست هم روی نسخه شما هم نسخه اصلی اونم اینکه  با فراگمنت مشکل داره و کار نمیکنه یا اگر هم کار بکنه خیلی سرعت پایینی داره. من روی رزبری پای 4 و آخرین ورژن 
openwrt تست کردم
 لطفا بررسی کنید

**Comment by amirhosseinchoghaei** [comment]
درود ، از ایکس ری ورژن 1.8.3 استفاده بفرمایید

**Comment by omidtb279** [comment]
چطوری به ایکس ری ورژن 1.8.3 دانگرید کنیم ؟

**Comment by amirhosseinchoghaei** [comment]
مشکل در ایکس ری های ورژن بالا برطرف شده دانگرید نکنید
