### ISSUE TITLE
problem with install cludflare

### ISSUE THREAD

**Issue by nader324** [amirhosseinchoghaei/Passwall#44]
hi dear amirhossein
/base/libreadline8_8.1-1_mipsel_24kc.ipk
Configuring terminfo.
Configuring libncurses6.
Configuring libreadline8.
Configuring bash.
Package curl (8.6.0-1) installed in root is up to date.
cdnopw.sh: line 1: syntax error near unexpected token `newline'
cdnopw.sh: line 1: `<!DOCTYPE html>'

**Comment by amirhosseinchoghaei** [comment]
try X86
