### ISSUE TITLE
GRPC not working - Wrong status

### ISSUE THREAD

**Issue by mahanhpn** [amirhosseinchoghaei/Passwall#45]
با عرض سلام
کانفیگ های grpc tls vmess کار نمیکنن
و با اینکه سرویس درحال کار هست و وی پی ان ست شده در قسمت داشبورد passwall وضعیت VPN status به صورت not running هست

**Comment by amirhosseinchoghaei** [comment]
Fixed

**Comment by mahanhpn** [comment]
مدل روتر 4a gigabit هست
بعد از تغییر نسخه openwrt به 22.3.3 که در readme اپدیت شده گفته بودید مشکل not running حل شد
اما متاسفانه هنوز کانفیگ vmess tls grpc وصل نمیشه
همین کانفیگ ها با همین اینترنت روی گوشی متصل هست و روی کلاینت های مختلف تست شده
چطوری میتونم مشکل رو پیدا کنم ؟
