### ISSUE TITLE
سلام

### ISSUE THREAD

**Issue by omidtb279** [amirhosseinchoghaei/Passwall#48]
سلام من مشکلی که روی روتر 4a نسخه giga  شیائومی دارم این هست که پروکسی هی قطع و وصل میشه راه حلی داری ؟

**Comment by amirhosseinchoghaei** [comment]
سلام رم پایینه روتر xiaomi ax 3000t بخرید موفق باشید

**Comment by omidtb279** [comment]
مدل linksys-ea8300 هم اکی هست بخرم ؟

**Comment by omidtb279** [comment]
1- ایا نصب اینکه فروشنده دی جی کالا گفته نسخه اینترنشنال روتر xiaomi ax 3000t دارای  openwrt از پیش نصب شده هست حقیقت داره ؟
2-  آیا نصب openwrt روی روتر xiaomi ax 3000t آسان هست ؟
3- آیا شما آموزشی در مورد نصب openwrt روی این روتر دارین ؟

**Comment by omidtb279** [comment]
> پیشنهاد نمیکنم

1- ایا نصب اینکه فروشنده دی جی کالا گفته نسخه اینترنشنال روتر xiaomi ax 3000t دارای openwrt از پیش نصب شده هست حقیقت داره ؟
2- آیا نصب openwrt روی روتر xiaomi ax 3000t آسان هست ؟
3- آیا شما آموزشی در مورد نصب openwrt روی این روتر دارین ؟

**Comment by amirhosseinchoghaei** [comment]
تهیه کنید مشکلی نداره ... فقط بعدش ایمیج رسمی را از سایت openert تهیه و جایگزین کنید

**Comment by omidtb279** [comment]
> تهیه کنید مشکلی نداره ... فقط بعدش ایمیج رسمی را از سایت openwrt تهیه و جایگزین کنید

ممنون

**Comment by omidtb279** [comment]
> تهیه کنید مشکلی نداره ... فقط بعدش ایمیج رسمی را از سایت openwrt تهیه و جایگزین کنید

ممکنه بگین دقیقا کدام نسخه ؟

**Comment by amirhosseinchoghaei** [comment]
https://downloads.openwrt.org/snapshots/targets/mediatek/filogic/openwrt-mediatek-filogic-xiaomi_mi-router-ax3000t-squashfs-sysupgrade.bin
