### ISSUE TITLE
Hello get eror for install pass wall 2 in mi4a giga

### ISSUE THREAD

**Issue by omidtb279** [amirhosseinchoghaei/Passwall#49]
Hello get eror for install pass wall 2 in mi4a giga

![Screenshot 2024-04-30 200300](https://github.com/amirhosseinchoghaei/Passwall/assets/111964469/dcfb74d8-b1fb-4c49-a450-b9a076a47d4a)
help me plz

**Comment by amirhosseinchoghaei** [comment]
Mi 4a Gigabit Not Support Passwall 2
