### ISSUE TITLE
Xray

### ISSUE THREAD

**Issue by tkmw1985** [amirhosseinchoghaei/Passwall#5]
Hello dear.  Installed successfully but after reboot, the xray core does not start.  Is it downloading again by the script each reboot into the temp folder?

**Comment by amirhosseinchoghaei** [comment]
Hi There , What is your Model of your router ?

**Comment by tkmw1985** [comment]
mi4a gigabit

**Comment by amirhosseinchoghaei** [comment]
IF You install the script Completely , After each reboot Xray-core will be install automatic. just in 3 min after boot ...

**Comment by tkmw1985** [comment]
I am trying to understand. How is the script do that downloading it
remotely from another source or locally from router?

вт, 3 окт. 2023 г., 15:21 AmirHosseinChoghaei ***@***.***>:

**Comment by tkmw1985** [comment]
If remotely then there's a problem for our country cuz almost every single
site got blocked.

вт, 3 окт. 2023 г., 15:28 Tkm Tkmaew ***@***.***>:

**Comment by amirhosseinchoghaei** [comment]
Its online

**Comment by tkmw1985** [comment]
Can we edit script  to download for example from another source which will
be uploaded by myself ? If yes can you point me which script should I edit
and download exactly ipk file to upload it to another source?

вт, 3 окт. 2023 г., 15:31 AmirHosseinChoghaei ***@***.***>:

**Comment by amirhosseinchoghaei** [comment]
Sure ...

https://github.com/amirhosseinchoghaei/Install-Xray-V2ray-On-Passwall-Openwrt/blob/765db44fb56bd917102a436d210ce275522ef7af/owo.sh#L31

* File that you want upload should be : panel.ipk

**Comment by tkmw1985** [comment]
Yes, the problem was solved already found two files panel.ipl and zip file
loaded to another source change link in owo script.

ср, 4 окт. 2023 г., 15:16 AmirHosseinChoghaei ***@***.***>:
