### ISSUE TITLE
remote dns

### ISSUE THREAD

**Issue by milad97** [amirhosseinchoghaei/Passwall#50]
سلام وقت بخیر
گزینه remote dns حذف شده داخل اپدیت جدید ؟ یه سری از سایت ها باز نمیشه وقتی وی پی ان وصله

**Comment by omidtb279** [comment]
> سلام وقت بخیر گزینه remote dns حذف شده داخل اپدیت جدید ؟ یه سری از سایت ها باز نمیشه وقتی وی پی ان وصله

سلام مدل روتر شما چیه ؟

**Comment by milad97** [comment]
ea7300 v2 256mb  ram
