### ISSUE TITLE
Rule Management

### ISSUE THREAD

**Issue by paytakhtgithub** [amirhosseinchoghaei/Passwall#52]
سلام،
من متوجه شدم علیرغم آپدیت کردن فایل های geosite و geoip رول هایی که بر اساس geosite هستن اعمال نمیشن و به روش دیفالت باهاشون برخورد میشه مثال geosite:playstation
در صورتی که رول هایی که بر اساس دامنه نوشته شدن به خوبی انجام میشن مثال domain:playstation.net
تنظیمات domain strategy هم روی IPifnonMatch هست

**Comment by amirhosseinchoghaei** [comment]
درود ، مدل روتر ؟

**Comment by paytakhtgithub** [comment]
میکروتیک RB750GR3
Ram: 256MB
CPU: 880MHz

**Comment by amirhosseinchoghaei** [comment]
به نظر میاد پکیج های geoip va geosite به دلیل کم بودن حافظه داخلی شما نصب نشده است ، با فلش مموری افزایش حجم انجام دادید ؟

**Comment by paytakhtgithub** [comment]
بله با اسکریپت شما و فلش ۸ گیگابایت افزایش دادم
حتی به صورت دستی هم دو تا فایل رو آپدیت کردم و چک کردم با ssh وجود دارن در روتر

**Comment by amirhosseinchoghaei** [comment]
opkg update
opkg install v2ray-geoip
opkg install v2ray-geosite

این دستور را اجرا بفرمایید ، در صورتی که این دو پکیج نصب نباشند مشکل شما رفع میشود
اما در صورتی که پکیج ها نصب بوده باشند شما یجای کار رو دارید اشتباه میکنید من از بابت این آپشن مطمن هستم و همین الان در حال حاضر برای من به درستی عمل میکند .

**Comment by paytakhtgithub** [comment]
هر دو پکیج ها نصب بودن و به روز
اما همچنان سایت های ایرانی باز نمیشن حتی با وجود رول geoip:ir در قسمت ip
![image](https://github.com/amirhosseinchoghaei/Passwall/assets/121974702/2257557a-8e42-4309-b01d-907b77ba6d1d)

**Comment by amirhosseinchoghaei** [comment]
لطفا تلگرام پیام بدید ...
