### ISSUE TITLE
error in installing dns2tcp

### ISSUE THREAD

**Issue by Alireza271** [amirhosseinchoghaei/Passwall#55]
Unknown package 'luci-app-passwall'.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency dns2tcp for luci-app-passwall
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-passwall found, but incompatible with the architect

**Comment by amirhosseinchoghaei** [comment]
از سایت openwrt ایمیج رسمی مربوط به روترتون رو دانلود و جایگزین کیند موفق باشید
