### ISSUE TITLE
سوال در مورد ax3000t

### ISSUE THREAD

**Issue by omidtb279** [amirhosseinchoghaei/Passwall#56]
سلام طبق توصیه شما روتر شیائومی ax3000t رو تهیه کردم و کاملا راضی هستم از خریدم و چند تا سوال داشتم 

![Screenshot 2024-05-31 103010](https://github.com/amirhosseinchoghaei/Passwall/assets/111964469/4ef1a121-036d-4196-aa7e-958fb5864238)
![Screenshot 2024-05-31 103428](https://github.com/amirhosseinchoghaei/Passwall/assets/111964469/6bc8f8e4-1683-4f42-b5f3-0e2093fc5142)
![Screenshot 2024-05-31 104047](https://github.com/amirhosseinchoghaei/Passwall/assets/111964469/1dfc19de-e01b-47bc-bc14-ad81a1951fbb)

1- ایا نسخه opwnwrt که الان نصب هست اخرین نسخه پایدار هست ؟
2- فرق بین Openwrt SNAPSHOT با Openwrt چیست ؟

**Comment by amirhosseinchoghaei** [comment]
سلام ، اسنپ شات در بعضی موارد حتی میتونه خیلی بهتر عمل کنه مخصوصا برای این روتر اسنپ شات به خوبی جواب میده .

**Comment by omidtb279** [comment]
> سلام ، اسنپ شات در بعضی موارد حتی میتونه خیلی بهتر عمل کنه مخصوصا برای این روتر اسنپ شات به خوبی جواب میده .

خیلی ممنون از پاسخگویی شما

![Screenshot 2024-05-31 105442](https://github.com/amirhosseinchoghaei/Passwall/assets/111964469/ca64c321-c263-43f8-bbf1-52a6af3cc7e7)
الان روی این نسخه passwall 2 نصب هست و اینکه نسخه اسنپ شات به روز هست ؟ چون داخل سایت دو نسخه هست نمیدونم فرقشون چی هست ؟ 
![Screenshot 2024-05-31 105651](https://github.com/amirhosseinchoghaei/Passwall/assets/111964469/f55de045-69a8-490f-baef-b353aefb0201)
](url)

**Comment by amirhosseinchoghaei** [comment]
این نسخه ای که برای شما نصبه نسخه کامپایل شده توسط فروشنده هستش و رسمی نیست اما اگر خوب کار میکنه و مشکلی ندارید تغییری ایجاد نکنید به نظر مشکلی نیست .
