### ISSUE TITLE
Error TPlink archer c6v3.2 128MB openwrt22.03.3

### ISSUE THREAD

**Issue by CyrusTheV** [amirhosseinchoghaei/Passwall#58]
سلام.روتر اینترنت داره ولی با خطای زیر روبرو میشه.

Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency dns2tcp for luci-app-passwall
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-passwall found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-passwall.
Package ipset (7.15-2) installed in root is up to date.
Package ipt2socks (1.1.4-3) installed in root is up to date.
Package iptables-nft (1.8.7-7) installed in root is up to date.
Package iptables-zz-legacy (1.8.7-7) installed in root is up to date.
Package iptables-mod-conntrack-extra (1.8.7-7) installed in root is up to date.
Package iptables-mod-iprange (1.8.7-7) installed in root is up to date.
Package iptables-mod-socket (1.8.7-7) installed in root is up to date.
Package iptables-mod-tproxy (1.8.7-7) installed in root is up to date.
Package kmod-ipt-nat (5.10.161-1) installed in root is up to date.
Package kmod-nft-socket (5.10.161-1) installed in root is up to date.
Package kmod-nft-tproxy (5.10.161-1) installed in root is up to date.
Archive:  iam.zip
  inflating: /lib/upgrade/keep.d/luci-app-passwall
  inflating: /usr/lib/lua/luci/view/passwall/global/status.htm
  inflating: /usr/lib/lua/luci/view/passwall2/global/status.htm
  inflating: /usr/lib64/lua/luci/view/passwall/global/status.htm
  inflating: /usr/lib64/lua/luci/view/passwall2/global/status.htm
ls: /etc/init.d/passwall: No such file or directory
 Can not Download Packages ... Check your internet Connection .

**Comment by amirhosseinchoghaei** [comment]
با اینترنت همراه اول چک کنید
