### ISSUE TITLE
مشکل - تغییر نکردن ای پی

### ISSUE THREAD

**Issue by shehnipoor** [amirhosseinchoghaei/Passwall#6]
سلام
من پسوال را با موفقیت روی روتر 4c شیایومی نصب کردم
اما کار نمیکنه
ای پی میگیرم ایران میزنه

**Comment by amirhosseinchoghaei** [comment]
سلام 4c قابلیت نصب ایکس ری را ندارد حجم کافی نمیباشد …

**Comment by shehnipoor** [comment]
اما موقع نصب هیچ خطایی نداد

**Comment by shehnipoor** [comment]
هیچ راهی وجود ندارد؟ چه روتری را پیشنهاد میکنید؟

**Comment by amirhosseinchoghaei** [comment]
TP-Link C6 V3

**Comment by shehnipoor** [comment]
روی 4a شیایومی هم نمیشه نصب کرد؟ و واسه 4c راهکاری ندارید؟
