### ISSUE TITLE
Load Balance

### ISSUE THREAD

**Issue by alivkz** [amirhosseinchoghaei/Passwall#60]
Hi. 
I set up the load balance on openwrt but when connected to the Passwall, it doesn't follow the load balance rule.
I assigned IPs to the source and destination in load balance rules. How can I access the port and IP of the Passwall to make rules?

**Comment by amirhosseinchoghaei** [comment]
Hi 
The Load-Balancer Provide a Socks Port , so you need to add node and set default node .
