### ISSUE TITLE
aya mishe kari krd vpn fght roye wifi ha kar kone?

### ISSUE THREAD

**Issue by aliblacck** [amirhosseinchoghaei/Passwall#61]
slm merc az proje awlit ishalla hamishe moafgh bashi
mikhastm bedonm mishe kari krdn vpn fght roye wifi ha savar she va yeki az port haye lan va kari krd ke 2ta port dg lan mostaqim be isp  asli vasl bashn

**Comment by amirhosseinchoghaei** [comment]
خیر اما از بخش access control میتونید مدیریت کنید که کدوم دستگاه بای پس بشه
