### ISSUE TITLE
طرز وارد کردن کلید ECH

### ISSUE THREAD

**Issue by Daariush** [amirhosseinchoghaei/Passwall#62]
سلام
چگونه باید محتویات کلید ECH را برای نود در پسوال وارد کرد؟
مثلا [
            "-----BEGIN ECH CONFIGS-----",
            "AFf+DQBTAAAgACB6W+9vL92rXF3Pjqo39EYyjO+aW5+dBKwV1INoV/1+cwAIAAEA",
            "AQABAAMAIFstLXBxLXNpZ25hdHVyZS1zY2hlbWVzLWVuYWJsZWRdAAA=",
            "-----END ECH CONFIGS-----"
          ]

**Comment by amirhosseinchoghaei** [comment]
درود ، همچین امکانی وجود ندارد

**Comment by Daariush** [comment]
<img width="687" alt="Screenshot 2024-07-18 at 13 35 27" src="https://github.com/user-attachments/assets/fdd4d339-7bc2-4676-81fa-ab3fc36c9782">

**Comment by amirhosseinchoghaei** [comment]
بله درست میفرمایید در از سینگ باکس هیستریا و توییک این قابلیت وجود داره 


متشکرم

**Comment by Daariush** [comment]
خب سوالم این هست که چطوری باید وارد بشه؟ در سوال اصلی کلید را گذاشتم، از کجاش باید گذاشت؟
