### ISSUE TITLE
عمل نکردن بخش direct list

### ISSUE THREAD

**Issue by travelagancy** [amirhosseinchoghaei/Passwall#65]
عرض سلام و احترام خدمت شما دوست گرامی

بنده یه مشکلی دارم، اینکه سایت هایی رو که در بخش direct list قرار میدم تا به صورت مستقیم و با آی پی ایران متصل بشه، گویا کار نمیکنه و تمامی سایت هایی که در بخش direct list هستند، از طریق پروکسی و با آی پی فیلتر شکن متصل میشه.
مودم  Xiaomi Mi 4A Gigabit Edition , و آخرین نسخه passwall  هم نصب کردم.

خیلی ممنون میشم که راهنماییم بفرمایید

**Comment by amirhosseinchoghaei** [comment]
ارادت ،
از قسمت basic بخش mode مقادیر را تغییر دهید

**Comment by travelagancy** [comment]
تشکر بابت پاسخگویی‌تون🙏🏼🙏🏼

![Untistled](https://github.com/user-attachments/assets/618cf052-fa18-4c2f-a243-b4462c8ef08d)

لطفا میفرمایید که در این بخش mode دقیقا کدوم مقادیر رو باید تغییر بدم تا direct list به درستی عمل کنه؟

**Comment by amirhosseinchoghaei** [comment]
اینجا بزارید روی گلوبال پروکسی و سیو کنید همچنین از بخش دایرکت لیست هم عکس بدید چه کانفیگی وارد فرمودین ؟

**Comment by travelagancy** [comment]
بخش دایرکت لیست همان سایت هایی هست که به صورت پیشفرض هنگام نصب بود
![Untitledaa](https://github.com/user-attachments/assets/ea474009-3503-4933-ab75-246a4ba68ce1)

به طور مثال از درگاه شاپرک (shaparak.ir) داخل دایرکت لیست قرار داره، اما وقتی از درگاه اینترنتی میخوام خرید کنم،  آی پی رو خارج از ایران تشخیس میده و حتما باید پروکسی رو قطع کنم

**Comment by amirhosseinchoghaei** [comment]
https://account.tamin.ir/auth/login

این سایت باز میشه ؟

**Comment by travelagancy** [comment]
بله باز میشه👍🏼

**Comment by amirhosseinchoghaei** [comment]
پس داره عمل میکنه دامنه شاپرکی که براتون باز نمیشه به صورت دستی اد کنید ، روترتون خیلی ضعیف هستش این روش دایرکت قدیمی میباشد روش بهتری برای دایرکت کردن ایران ترافیک هست که نیازمند رم 256 میباشد ... موفق باشید

**Comment by travelagancy** [comment]
دست گلتون درد نکنه، یک دنیا سپاس🌸🌸🌸
