### ISSUE TITLE
direct app

### ISSUE THREAD

**Issue by arash1959** [amirhosseinchoghaei/Passwall#67]
سلام مهندس  آیا امکانش هست یک اپلکیشن رو دایرکت کرد رو اندروئید یا هر سیسنم عاملی  مثلا اپلکیشن صرافی  که فیلتر نیست سپاس

**Comment by amirhosseinchoghaei** [comment]
ارادت ، آی پی لیست و دامین لیست های اپلیکیشن مربوطه را در بخش دایکرت کانکشن اد کنید
