### ISSUE TITLE
Core NOT RUNNING

### ISSUE THREAD

**Issue by arash1959** [amirhosseinchoghaei/Passwall#69]
سلام مهندس خسته نباشید امروز x جایگزین اینستا شده در قسمت بیسیک ستینگ ولی مشکل Core NOT RUNNING  پیش امد در حالیکه همه چیز درست کار میکنه و ارتباط وی پی ان برقراره

**Comment by amirhosseinchoghaei** [comment]
ارادت ، باگ برطرف شد ممنون از اطلاع شما ، روتر رو یکبار خاموش روشن کنید لطفا ... اگر مشکل پا برجا بود اطلاع بدید .

**Comment by arash1959** [comment]
سپاس من هم آپدیت کردم هم روتر رو ریبوت کردم ولی متاسفانه همچنان  مشکل پا برجاست البته مشکلی در کارکرد نیست فقط نات رانینگ نمایش داده میشه

**Comment by amirhosseinchoghaei** [comment]
مجدد روتر رو خاموش روشن بفرمایید من تغییرات را اعمال کردم نتیجه را اعلام کنید

**Comment by arash1959** [comment]
![Core NOT RUNNING](https://github.com/user-attachments/assets/13124425-72e7-4fda-b79c-6f1b4e929e23)
![Core](https://github.com/user-attachments/assets/1bfee756-522c-4600-ae30-2e072b06f564)

**Comment by amirhosseinchoghaei** [comment]
مجدد روتر را خاموش روشن بفرمایید اپدیت جدید اعمال شد

**Comment by arash1959** [comment]
![Screenshot_20240924_211826_Edge](https://github.com/user-attachments/assets/5ec0d0fb-2600-4e92-bd46-71560046b110)
با این آپدیت مشکل حل شد مهندس سپاس از زحمات شما
