### ISSUE TITLE
Mobinnet Internet Can't install Passwall Packages

### ISSUE THREAD

**Issue by arash1959** [amirhosseinchoghaei/Passwall#7]
مهندس جان با مبین نت هم نصب نمیشه کرد من با اینترنت صفر و یک انجام دادم  گفتم جهت اصلاع رسانی سپاس

**Comment by amirhosseinchoghaei** [comment]
درود ، با صفر و یک کامل نصب شد اسکریپت براتون ؟

**Comment by arash1959** [comment]
بله بدون هیج مشکلی
