### ISSUE TITLE
اضافه کردن هسته مهسا

### ISSUE THREAD

**Issue by asghar61** [amirhosseinchoghaei/Passwall#70]
سلام . آقا دمت گرم چه اسکریپت جالبی .میتونی هسته مهسا رو استفاده کنی که از فرگمنت قسمت پکت رو بتونیم tlshello  بزاریم . بازم ممنون بابت کار جالبی که کردی

**Comment by amirhosseinchoghaei** [comment]
ارادت ، بله حتما . مدل روترتون را اعلام کنید اینجا

**Comment by asghar61** [comment]
دمت گرم . یه ویدئو ازش میزارم کارت خیلی باحال بود .

**Comment by asghar61** [comment]
![17287120535124804720820615631152](https://github.com/user-attachments/assets/c52512fb-13f3-4ff9-b2b4-e1b20ab4a895)
امیر حسین جان خطا در آپدیت کور مهسا

**Comment by amirhosseinchoghaei** [comment]
مدل روتر را اعلام بفرمایید ...

**Comment by amirhosseinchoghaei** [comment]
مجدد نصب بفرمایید تغییرات اعمال شد .

rm -f passwallx.sh && wget https://raw.githubusercontent.com/amirhosseinchoghaei/Passwall/main/passwallx.sh && chmod 777 passwallx.sh && sh passwallx.sh

**Comment by asghar61** [comment]
مرسی از سرعت عمل . رو پی سی نصبه x86 -64

**Comment by amirhosseinchoghaei** [comment]
چک فرمودین ؟ توی قسمت app update ایکس ری رو آپدیت کنید و اگر گفت آپدیته فورس آپدیت را بزنید .

**Comment by asghar61** [comment]
باشه - بزار تست کنم

**Comment by asghar61** [comment]
![1728722534162881737212706731673](https://github.com/user-attachments/assets/a1e155d3-db41-4c06-9ffd-955f9fd2e490)
 موقع نصب خطا میده

**Comment by amirhosseinchoghaei** [comment]
>/usr/lib/lua/luci/passwall2/com.lua


curl https://raw.githubusercontent.com/amirhosseinchoghaei/Passwall/refs/heads/main/com >>/usr/lib/lua/luci/passwall2/com.lua


این دوتا رو به ترتیب توی ssh بزن

**Comment by asghar61** [comment]
قدایی داری  اوکی شد
