### ISSUE TITLE
Passwall 1 / Mahsa Core

### ISSUE THREAD

**Issue by arash1959** [amirhosseinchoghaei/Passwall#71]
سلام مهندس گویا باید فکر روتر ۲۵۶ باشیم برای استفاده از هسته مهسا آیا امکان داره رو ۱۲۸ بشه استفاده کرد اگر نه روتر 3000t بگیریم نسبت به بقیه بهتره آیا سپاس روتر فعلی  Xiaomi Mi Router 4A Gigabit Edition

**Comment by amirhosseinchoghaei** [comment]
ارادت ، 3000t  تهیه بفرمایید لطفا
