### ISSUE TITLE
Not being able to install on AX3000T

### ISSUE THREAD

**Issue by hamedunix** [amirhosseinchoghaei/Passwall#77]
با سلام،
متاسفانه با پیروی از آموزش شما قادر به نصب passwall روی ax3000T  نمیشوم و چنین پیام خطایی را دریافت میکنم.
![image](https://github.com/user-attachments/assets/2ed933c0-68e7-4396-93db-0a79096ed2b4)

البته این خطا در انتهای نصب رخ میدهد و قبل از این هم خطاهایی را نمایش میدهد از جمله:
*** Failed to download the package list from https://master.dl.sourceforge.net/project/openwrt-passwall-build/releases/packages-23.05/aarch64_cortex-a53/passwall_packages/Packages.gz

**Comment by amirhosseinchoghaei** [comment]
اگر در دانلود بسته‌های Passwall2 از مخزن Sourceforge مشکل دارید، از پنل روتر وارد قسمت Software و configure opkg بشید
هر جا آدرس sourceforge هست
master.dl.sourceforge.net
 به این تغییرش بدید:

kumisystems.dl.sourceforge.net
یا اینها:
netcologne.dl.sourceforge.net
phoenixnap.dl.sourceforge.net
netix.dl.sourceforge.net
