### ISSUE TITLE
نصب روی رزبری

### ISSUE THREAD

**Issue by shehnipoor** [amirhosseinchoghaei/Passwall#8]
سلام
من پسوال را روی رزبری نصب کردم

به وای فای که متصل میشم نت از مودم را دریافت و شیر نمیکند

مشکل چیست؟

**Comment by amirhosseinchoghaei** [comment]
درود بر شما ریست فکتوری کنید و در اولین گام وای فای دستگاه را کانفیگ و تست بفرمایید ، بعد پکیج های مد نظر رو نصب کنید ...

**Comment by shehnipoor** [comment]
البته به وای فاتی رزبری که وصل میشم اینترنت میده
اما ای پی dhcp مودم رو داره میگیره
همین کاری ک گفتید را انجام بدم؟

**Comment by amirhosseinchoghaei** [comment]
متوجه نمیشم ... !

الان رزبری پای رو با وای فای به مودم اینترنت وصل میکنید و نتیجه نمیگیرد 
یا اینکه گوشی شما وقتی به رزبری پای وصل میشه هیچ دیتایی ندارید ؟

کدوم حالت ؟

**Comment by shehnipoor** [comment]
ببینید
من با گوشی به VPN 2G متصل شدم
رزبری هم با کابل لن به مودم وصله
اینترنت داره
اما داره dhcp رو از مودم میگیره نه از رزبری
ای پی مودم من 192.168.1.2 هستش
وقتی تنظیمات وای فای VPN 2G رو روی گوشی نگاه میکنم میبینم که gatway 192.168.1.2 هستش

در صورتی که ای پی رزبری 192.168.27.1 هستش

**Comment by shehnipoor** [comment]
وقتی هم کانکشن گوشی را از dhcp  روی static میزارم و gatway را 192.168.27.1 قرار میدم
اینترنت نمیگیره دیگ

**Comment by amirhosseinchoghaei** [comment]
رزبری شما تک پورت لن هستش درسته ؟

**Comment by shehnipoor** [comment]
بله

**Comment by shehnipoor** [comment]
میخوام از لن نت رو بگیره و از طریق وای فای شیر کنه

**Comment by amirhosseinchoghaei** [comment]
مشکل همینجاست تک پورت نمیتونه هم نت بگیره هم دی اپ سی پی بشه مگر بره توی بحث وی لن بندی و اینا که با openwrt من تجربه این کار رو ندارم متاسفانه ....

**Comment by shehnipoor** [comment]
قرار نیست لن هردو باشه
لن فقط کار دریافت نت رو قراره بکنه و سیستم ها قراره از وای فای dhcp بگیرن

**Comment by amirhosseinchoghaei** [comment]
خب DHCP شما غیر فعال هستش و وای فای شما با لن شما ترکیب شده هستش ... باید برید بخش بخش جدا کنید از br-lan خارج کنید وای فای را و یک اینترفیس مستقل تشکیل بدید ... من باز میگم تاحالا این کار رو انجام ندادم اما مشکل شما دقیقا اینجاست که دی اچ سی پی افتاده روی مودم اصلی به خاطر این قضایا

**Comment by shehnipoor** [comment]
یک اینترفیس جدید از نوع dhcp روی lan-brig ساختم و مشکل حل شد

ممنونم از شما بابت اسکریپت خوبتون
