### ISSUE TITLE
Passwall installation solution with all operators and ISPs

### ISSUE THREAD

**Issue by arash1959** [amirhosseinchoghaei/Passwall#9]
سلام مهندس جان با انجام چندین بار تست به این نتیجه رسیدم که با ست کردن لوکیشن و تایم اپن دبلیوآرتی روی ایران قبل از نصب پسوال به راحتی نصب انجام میشه بقیه هم تست کنن این راه رو با سپاس

**Comment by amirhosseinchoghaei** [comment]
درود بر شما ، سپاس بابت به اشتراک گذاشتنتون
https://github.com/amirhosseinchoghaei/Passwall/blob/e97bfbe20cdb808a66d7de1b316fa4fcbc962eba/passwallx.sh#L17
قبل از نصب پکیج درون اسکریپت درج شد ...
